/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103C6_LCD.h"
#include "STM32F103C6_GPIO.h"
#include "STM32F103C6_KEYPAD.h"
#include "STM32F103C6_EXTERNALINTERRUPTS.h"




int main(void) {

	/* Write your application code here */

	while (1) {

	}
}


